# Generated by Django 4.2.3 on 2023-07-16 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prose.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabilitationCenter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('description', prose.fields.RichTextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rehabilitation_centers', to='core.city')),
                ('inclusions', models.ManyToManyField(to='core.inclusiontag')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rehabilitation_centers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Центр реабилитации',
                'verbose_name_plural': 'Центры реабилитации',
                'ordering': ['name'],
            },
        ),
    ]
